spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    database: sql_server
    ddl-auto: update
    #    show-sql: true
    database-platform: org.hibernate.dialect.SQLServer2008Dialect

  application:
    name: hydro-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/

TestBean:
  name: hahaha
  age: 13

#server:
#  port: 8866