spring:
  main:
    allow-bean-definition-overriding: true

  application:
    name: hydro-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/

TestBean:
  name: hahaha
  age: 13